### ISSUE TITLE
列表复用问题

### ISSUE THREAD

**Issue by lieoo** [boyssimple/AtChat#1]
在有语音、图片、文本的情况下，文本和语音背景会有复用问题
![simulator screen shot 2017 4 13 1 29 53](https://cloud.githubusercontent.com/assets/15972623/24991424/5424adb0-204d-11e7-82c0-311aeae36ce0.png)
![simulator screen shot 2017 4 13 1 29 58](https://cloud.githubusercontent.com/assets/15972623/24991425/544c1454-204d-11e7-9409-578db367b974.png)
![simulator screen shot 2017 4 13 1 30 00](https://cloud.githubusercontent.com/assets/15972623/24991426/544e6fc4-204d-11e7-8b29-47e4f32ec94f.png)

**Comment by boyssimple** [comment]
什么环境下的

**Comment by lieoo** [comment]
环境？你是指运行环境？
10.1 6S模拟器

**Comment by lieoo** [comment]
又试了一下，在聊天过程中，使用文本和语音时，没有这种复用问题。
存在发送图片的情况下，上下滚动后进入复用池取出时就会有背景显示不全的情况。

您可以试一下，可以复现

**Comment by boyssimple** [comment]
OK，我这边处理下。

**Comment by lieoo** [comment]
等您。
我这边昨日 Fork 了您的项目，已经实现了播放语音功能，我还会继续向上开发例如实现语音聊天、视频聊天功能，以后再PR
