### ISSUE TITLE
对话气泡方向错误

### ISSUE THREAD

**Issue by lieoo** [boyssimple/AtChat#2]
![simulator screen shot 2017 4 13 6 26 11](https://cloud.githubusercontent.com/assets/15972623/25001173/c175e0b8-2076-11e7-9b2b-c95fb10b232e.png)

对话气泡方向错误

**Comment by lieoo** [comment]
这里 self.msg.outgong 类型为 number
应该这样：
  if([self.msg.outgoing isEqual: @(1)]){
        self.containerImageView.image = [self stretchImage:@"SenderTextNodeBkg"];
    }else{
        self.containerImageView.image = [self stretchImage:@"ReceiverTextNodeBkg"];
    }

**Comment by boyssimple** [comment]
我提交了，改的时候改错了，应该是isOutgoing
