### ISSUE TITLE
您好，想咨询个问题

### ISSUE THREAD

**Issue by lieoo** [boyssimple/AtChat#3]
在消息界面，获取聊天记录时，能否做到按照最后会话时间的戳倒叙排列 像微信一样，这里是否可以优化一下？
NSPredicate 可以做到吗

**Comment by boyssimple** [comment]
应该是可以的，我看有空优化下

**Comment by boyssimple** [comment]
已处理

**Comment by boyssimple** [comment]
我加了个视频通话
 
 
------------------ Original ------------------
From: "lieoo"; 
Date: 2017年4月17日(星期一) 下午4:09
To: "boyssimple/AtChat"; 
Cc: "boyssimple"; "Comment"; 
Subject: Re: [boyssimple/AtChat] 您好，想咨询个问题 (#3)

 

Closed #3.

**Comment by lieoo** [comment]
请教一下 WebRTC 这边 您服务端是怎么做的

**Comment by lieoo** [comment]
最近这里两天在研究 群聊功能，遇到了好多坑 网上的资料也很少。
比如您的 XmppTools.m 里面 
`    [_xmppAutoPing setPingInterval:1];`
这里不应该 arg 不应该为 1 。这个方法会影响到 群聊功能接受响应方法
`- (BOOL)xmppStream:(XMPPStream *)sender didReceiveIQ:(XMPPIQ *)iq{}` 
arg 为 1 的话 这个方法大约一秒走一次这个方法，很消耗性能。我目前填写的是 1000.

**Comment by boyssimple** [comment]
嗯嗯，之前测试的时候改的1，后面找个时间加上群聊吧
 
 
------------------ Original ------------------
From: "lieoo"; 
Date: 2017年4月20日(星期四) 中午1:13
To: "boyssimple/AtChat"; 
Cc: "boyssimple"; "Comment"; 
Subject: Re: [boyssimple/AtChat] 您好，想咨询个问题 (#3)

 

最近这里两天在研究 群聊功能，遇到了好多坑 网上的资料也很少。
 比如您的 XmppTools.m 里面
 [_xmppAutoPing setPingInterval:1];
 这里不应该 arg 不应该为 1 。这个方法会影响到 群聊功能接受响应方法
 - (BOOL)xmppStream:(XMPPStream *)sender didReceiveIQ:(XMPPIQ *)iq{}
 arg 为 1 的话 这个方法大约一秒走一次这个方法，很消耗性能。我目前填写的是 1000.

**Comment by lieoo** [comment]
群聊这里我写了一部分 目前只实现了 加入、创建群聊功能。
这里蛮恶心的，比如 用户离线了以后 房间列表里就不存在这个用户了 还没处理
我正在写群聊天记录功能，头很大 还不知道怎么下手

**Comment by boyssimple** [comment]
加Q聊吧,499926249
 
 
------------------ Original ------------------
From: "lieoo"; 
Date: 2017年4月20日(星期四) 下午3:29
To: "boyssimple/AtChat"; 
Cc: "boyssimple"; "Comment"; 
Subject: Re: [boyssimple/AtChat] 您好，想咨询个问题 (#3)

 

群聊这里我写了一部分 目前只实现了 加入、创建群聊功能。
 这里蛮恶心的，比如 用户离线了以后 房间列表里就不存在这个用户了 还没处理
 我正在写群聊天记录功能，头很大 还不知道怎么下手
