### ISSUE TITLE
兄弟，编译不了，有问题 

### ISSUE THREAD

**Issue by Insfgg99x** [boyssimple/AtChat#5]
![编译错误](https://user-images.githubusercontent.com/12442442/34601650-f2159982-f237-11e7-8976-f5f565f05a99.png)

**Comment by boyssimple** [comment]
没有WebRTCClient.o这个呀，加进入就可以了
 
 
------------------ 原始邮件 ------------------
发件人: "CGPointZero"<notifications@github.com>;
发送时间: 2018年1月5日(星期五) 下午4:46
收件人: "boyssimple/AtChat"<AtChat@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [boyssimple/AtChat] 兄弟，编译不了，有问题 (#5)

**Comment by Insfgg99x** [comment]
怎么添加，你可以搞好我直接克隆下来就能编译吗？

**Comment by boyssimple** [comment]
我上传到云盘了呀，弄进去就可以了

 
 
------------------ 原始邮件 ------------------
发件人: "CGPointZero"; 
发送时间: 2018年1月6日(星期六) 上午10:21
收件人: "boyssimple/AtChat"; 
抄送: "boyssimple"; "Comment"; 
主题: Re: [boyssimple/AtChat] 兄弟，编译不了，有问题 (#5)

 

怎么添加，你可以搞好我直接克隆下来就能编译吗？

**Comment by Insfgg99x** [comment]
嗯，感谢啊
